### ISSUE TITLE
ExtJS 6.0.0.415 beta is out

### ISSUE THREAD

**Issue by choweiyuan** [webjars/extjs#14]
http://cdn.sencha.com/ext/beta/ext-6.0.0.415.zip

**Comment by jamesward** [comment]
WebJars can only redistribute the GPL version of ExtJS.  Can you point me to the GPL download for that version?

**Comment by choweiyuan** [comment]
No GPL for the beta :(

https://www.sencha.com/forum/showthread.php?300091-free-version-of-ExtJS-6&p=1096356&viewfull=1#post1096356

I'll close this issue
