### ISSUE TITLE
Please Release Version: 3.4.3

### ISSUE THREAD

**Issue by Idanatcox** [webjars/extjs#20]
Thanks in advance!
Love your website

**Comment by jamesward** [comment]
I can't seem to find the download for that anywhere.  Can you point me to it?

**Comment by Idanatcox** [comment]
it looks like this version was released to subscribers only so I guess we can't.
"Ext JS 3.4.3 has been released to support subscribers only on October 21, 2014. You can download it in the support portal (https://support.sencha.com). "
Thanks for the quick support
